# Generated by Django 6.0.3 on 2026-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
