# Generated by Django 6.0.3 on 2026-04-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transfer_date_alter_transfer_from_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=15),
        ),
    ]
