# Generated by Django 6.0.3 on 2026-04-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_tournament_season_match_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='prize_pool',
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('league', 'League'), ('playoff', 'Play-off')], default='league', max_length=10),
        ),
    ]
