# Generated by Django 6.0.3 on 2026-04-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tournament_prize_pool_tournament_prize_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
