# Generated by Django 6.0.3 on 2026-04-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tournament_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_club',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_club',
            new_name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.AddField(
            model_name='match',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tournament'),
        ),
    ]
