# Generated by Django 6.0.3 on 2026-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_away_club_match_away_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_starting',
            field=models.BooleanField(default=False),
        ),
    ]
