# Generated by Django 6.0.3 on 2026-04-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_club_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
    ]
